# Билет 1
## Задание 1
Реализуйте программный код, выполняющий сортировку матрицы
методом выбора. На вход программе дается матрица, которая
содержит в себе значения от -250 до 2000. Программа должна
возвращать матрицу в отсортированном виде.


In [53]:
#Я не уверен, что ето работает
import random 
import numpy
import time

def selection_sort(arr):
    for n in range(len(arr)):
        i=0
        while i < len(arr[0]) - 1:
            m = i
            j = i + 1
            while j < len(arr[0]):
                if arr[n][j] < arr[n][m]:
                    m = j
                j += 1
            arr[n][i], arr[n][m] = arr[n][m], arr[n][i]
            i += 1
    return arr

m = 3
n = 3
matrix = numpy.empty((m, n))
for i in range(m):
    for j in range(n):
        matrix[i][j] = random.randint(-250, 2000)
print(matrix)
selection_sort(matrix)
print(matrix)


[[1520.  596. 1390.]
 [1704.  592. 1091.]
 [ 581. 1590.  -55.]]
[[ 596. 1390. 1520.]
 [ 592. 1091. 1704.]
 [ -55.  581. 1590.]]


## Задание 2
Реализуйте программный код, выполняющий поиск методом
бинарного поиска. На вход программе дается отсортированный
массив, который содержит в себе значения от -250 до 2000 и
искомый элемент. Программа должна возвращать индекс искомого
элемента, либо уведомить пользователя, если такой элемент
отсутствует


In [54]:
def binary_search(a, value):
    mid = len(a) // 2
    low = 0
    high = len(a) - 1

    while a[mid] != value and low <= high:
        if value > a[mid]:
            low = mid + 1
        else:
            high = mid - 1
        mid = (low + high) // 2

    if low > high:
        return -1
    else:
        return mid

arr = [12, 24, 32, 39, 45, 50, 54] 
n = 45 

print(binary_search(arr, n) )

4


## Задание 3
Реализовать поиска подстроки в строке методом
Кнута-Морриса-Пратта. На вход программе подается строка и
подстрока. Программа должна быть чувствительной к строке и
регистру


In [55]:
# def prefix(t):
#     v = [0]*len(t)
#     for i in range(1,len(t)):
#         k = v[i-1]
#         while k > 0 and t[k] != t[i]:
#             k = v[k-1]
#         if t[k] == t[i]:
#             k = k + 1
#         v[i] = k
#     return v
# def kmp(s,t):

#     index = -1
#     f = prefix(t)
#     print(f)
#     k = 0
#     for i in range(len(s)):
#         while k > 0 and t[k] != s[i]:
#             k = f[k-1]
#         if t[k] == s[i]:
#             k = k + 1
#         if k == len(t):
#             index = i - len(t) + 1
#             break
#     return index
def prefix(t):
    p = [0]*len(t)
    j = 0
    i = 1

    while i < len(t):
        if t[j] == t[i]:
            p[i] = j+1
            i += 1
            j += 1
        else:
            if j == 0:
                p[i] = 0;
                i += 1
            else:
                j = p[j-1]
    return p
def kmp (s,t):
    m = len(t)
    n = len(s)
    p = prefix(t)
    i=0
    j=0
    while i<n:
        if s[i] == t[j]:
            i+=1
            j+=1
            if j == m:
                return i - len(t) + 1
        else: 
            if j>0:
                j = p[j-1]
            else:
                i += 1
    if i == n and j != m:
        return -1

print(kmp("st32staaStrstroka", "str"))

12


## Задание 4
На вход программе подается строка, содержащая набор слов
разделенных пробелом. Используя два дека, выполните сортировку
слов в алфавитном порядк

In [56]:
class deq:
    def __init__(self):
        self.deqs=list()
        
    #добавление в конец дека
    def add_left(self, el):
        self.deqs.insert(0, el)
        
    #добавление в начало дека
    def add_right(self, el):
        self.deqs.append(el)
        
    #проверка дека на пустоту
    def testing_null(self):
        return len(self.deqs)==0
    
    #извлечение элемента из начала дека
    def pop_right(self):
        if self.testing_null():
            return None
        else:
            return self.deqs.pop()
        
    #посмотреть элемент из конца
    def peek_left(self):
        if self.testing_null():
            return None
        else:
            return self.deqs[0]
        
    #посмотреть элемент с начала    
    def peek_rigth(self):
        if self.testing_null():
            return None
        else:
            return self.deqs[-1]
        
    #извлечение элемента из конца дека
    def pop_left(self):
        if self.testing_null():
            return None
        else:
            return self.deqs.pop(0)

str = "хотеться большинство разводить план яркий исключать установка бабах"
deq1 = deq()
deq2 = deq()
for i in str.split():
    deq1.add_left(i)
while not deq1.testing_null():
#     print(deq1.deqs, deq2.deqs)
    elem = deq1.pop_left()
    while not deq2.testing_null() and deq2.peek_left()<elem:
        deq1.add_right(deq2.pop_left())
    deq2.add_left(elem)
    
    
print(deq2.deqs)


['бабах', 'большинство', 'исключать', 'план', 'разводить', 'установка', 'хотеться', 'яркий']


# Билет 2
## Задание 1
Реализовать поиска подстроки в строке методом
Кнута-Морриса-Пратта. На вход программе подается строка и
подстрока. Программа должна быть не чувствительной к строке и
регистру


In [57]:
def prefix(t):
    p = [0]*len(t)
    j = 0
    i = 1

    while i < len(t):
        if t[j] == t[i]:
            p[i] = j+1
            i += 1
            j += 1
        else:
            if j == 0:
                p[i] = 0;
                i += 1
            else:
                j = p[j-1]
    return p
def kmp (s,t):
    s = s.lower()
    t = t.lower()
    m = len(t)
    n = len(s)
    p = prefix(t)
    i=0
    j=0
    while i<n:
        if s[i] == t[j]:
            i+=1
            j+=1
            if j == m:
                return i - len(t) + 1
        else: 
            if j>0:
                j = p[j-1]
            else:
                i += 1
    if i == n and j != m:
        return -1

print(kmp("st32staaStrstroka", "str"))

9


## Задание 2
Реализуйте программный код, выполняющий поиск методом
бинарного дерева. На вход программе дается отсортированный
массив, который содержит в себе значения от -250 до 2000 и
искомый элемент. Программа должна возвращать индекс искомого
элемента, либо уведомить пользователя, если такой элемент
отсутствует

In [1]:
class TreeNode:
    def __init__(self, value):
        self.value=value
        self.right=None
        self.left=None
    def add(self, mas):
        if mas<self.value:
            if self.left is None:
                self.left=TreeNode(mas)
            else:
                self.left.add( mas)
        else:
            if self.right is None:
                self.right=TreeNode(mas)
            else:
                self.right.add(mas)
        
            
    def search(self, nl):
        if nl and self and self.value is not None:
            if nl>self.value and self.right:
                self=self.right.search(nl)
            elif nl<self.value and self.left:
                self=self.left.search(nl)
            elif(nl==self.value):
                print("Элемент найден")
                return True
            else:
                print("Элемент не найден")
                return None
            
        else:
            print("Элемент не найден")
            return None
        return True
    def deleted(self):
        if self.right is not None:
            self.value=self.right.value
            self.right.deleted()
        elif self.left is not None:
            self.value=self.left.value
            self.left.deleted()
        elif (self.left is None) and (self.right is None):
            self.value=None
    
    def delete(self, i):
        self.pre_order(i).deleted()
        
    def pr(self):
        if self.left:
            self.left.pr()
        print(self.value)
        if self.right:
            self.right.pr()
arr = [12, 24, 32, 39, 45, 50, 54] 
n = 45 
tree=TreeNode(arr[0])
for i in range(1, len(arr)):
    tree.add(arr[i])
print(tree.search(n) )

Элемент найден
True


## Задание 3
Реализуйте программный код, выполняющий сортировку матрицы
методом вставки. На вход программе дается матрица, которая
содержит в себе значения от -250 до 2000. Программа должна
возвращать матрицу в отсортированном виде.

In [58]:
#Я не уверен, что ето работает
import random 
import numpy
import time
def insertion_sort(matrix):
    for row in matrix:
        for i in range(len(row)):
            j = i - 1 
            key = row[i]
            while row[j] > key and j >= 0:
                row[j + 1] = row[j]
                j -= 1
                row[j + 1] = key
    return matrix 

m = 3
n = 3
matrix = numpy.empty((m, n))
for i in range(m):
    for j in range(n):
        matrix[i][j] = random.randint(-250, 2000)
print(matrix)
selection_sort(matrix)
print(matrix)

[[ 985.   40. 1933.]
 [ 360. -117.  248.]
 [1972.  511. 1232.]]
[[  40.  985. 1933.]
 [-117.  248.  360.]
 [ 511. 1232. 1972.]]


## Задание 4

На вход программе дается строка, содержащая буквы и цифры.
Используя стек, напечатать сначала все цифры, затем все буквы

In [59]:
class stack:
    def __init__(self):
        self.stacks=list()
    def __len__(self):
        return len(self.stacks)
        
    # добавление элемента в стек
    def add(self, el):
        self.stacks.append(el)
        
    #проверка стека на пустоту
    def testing_null(self):
        return len(self.stacks)==0
    
    #извлечение элемента из стека
    def pop(self):
        if self.testing_null():
            return None
        else:
            return self.stacks.pop()
    
    def peek(self):
        if self.testing_null():
            return None
        else:
            return self.stacks[-1]

st = "312asd121assd213ad6747"
digit = stack()
letters = stack()
i = len(st) - 1
while i>=0:
    if st[i].isdigit():
        digit.add(st[i])
    else:
        letters.add(st[i])
    i-=1
out = "Цифры: "
while not digit.testing_null():
    out+=digit.pop()
print(out)
out = "Буквы: "
while not letters.testing_null():
    out+=letters.pop()
print(out)



Цифры: 3121212136747
Буквы: asdassdad


# Билет 3
## Задание 1
Реализовать поиска подстроки в строке методом
Кнута-Морриса-Пратта. На вход программе подается строка и
подстрока. Программа должна быть не чувствительной к строке и
регистру


In [60]:
def prefix(t):
    p = [0]*len(t)
    j = 0
    i = 1

    while i < len(t):
        if t[j] == t[i]:
            p[i] = j+1
            i += 1
            j += 1
        else:
            if j == 0:
                p[i] = 0;
                i += 1
            else:
                j = p[j-1]
    return p
def kmp (s,t):
    s = s.lower()
    t = t.lower()
    m = len(t)
    n = len(s)
    p = prefix(t)
    i=0
    j=0
    while i<n:
        if s[i] == t[j]:
            i+=1
            j+=1
            if j == m:
                return i - len(t) + 1
        else: 
            if j>0:
                j = p[j-1]
            else:
                i += 1
    if i == n and j != m:
        return -1

print(kmp("st32staaStrstroka", "str"))

9


## Задание 2
На вход программе дается строка, в которой содержится набор
положительным и отрицательных чисел. Используя дек, напечатать
сначала все отрицательные числа, затем все положительные числа,
сохраняя исходный порядок в каждой группе

In [61]:
class deq:
    def __init__(self):
        self.deqs=list()
        
    #добавление в конец дека
    def add_left(self, el):
        self.deqs.insert(0, el)
        
    #добавление в начало дека
    def add_right(self, el):
        self.deqs.append(el)
        
    #проверка дека на пустоту
    def testing_null(self):
        return len(self.deqs)==0
    
    #извлечение элемента из начала дека
    def pop_right(self):
        if self.testing_null():
            return None
        else:
            return self.deqs.pop()
        
    #посмотреть элемент из конца
    def peek_left(self):
        if self.testing_null():
            return None
        else:
            return self.deqs[0]
        
    #посмотреть элемент с начала    
    def peek_rigth(self):
        if self.testing_null():
            return None
        else:
            return self.deqs[-1]
        
    #извлечение элемента из конца дека
    def pop_left(self):
        if self.testing_null():
            return None
        else:
            return self.deqs.pop(0)

st = "2 -2 1 33 -21 2 3 5 -3"
my_deq = deq()
for i in st.split():
#     print(i)
    num = int(i)
#     print(num)
    if num >=0:
        my_deq.add_right(num)
    else:
        if my_deq.testing_null() or my_deq.peek_left()>=0:
            my_deq.add_left(num)
        else:
            count = 0 
            while my_deq.peek_left()<0:
                my_deq.add_right(my_deq.pop_left())
                count+=1
            my_deq.add_left(num)
            while count > 0:
                my_deq.add_left(my_deq.pop_right())
                count-=1
            
while not my_deq.testing_null():
    print(my_deq.pop_left())

-2
-21
-3
2
1
33
2
3
5


## Задание 3
Реализуйте программный код, выполняющий поиск методом
Фибоначчиева поиска. На вход программе дается отсортированный
массив, который содержит в себе значения от -250 до 2000 и
искомый элемент. Программа должна возвращать индекс искомого
элемента, либо уведомить пользователя, если такой элемент
отсутствует.


In [2]:
def fibMonaccianSearch(arr, x):
    n = len(arr)
    fibMMm2 = 0
    fibMMm1 = 1  
    fibM = fibMMm2 + fibMMm1

    while (fibM < n):
        fibMMm2 = fibMMm1
        fibMMm1 = fibM
        fibM = fibMMm2 + fibMMm1

    offset = -1

    while (fibM > 1):
 
        i = min(offset+fibMMm2, n-1)
 
        if (arr[i] < x):
            fibM = fibMMm1
            fibMMm1 = fibMMm2
            fibMMm2 = fibM - fibMMm1
            offset = i
 
        elif (arr[i] > x):
            fibM = fibMMm2
            fibMMm1 = fibMMm1 - fibMMm2
            fibMMm2 = fibM - fibMMm1
 
        else:
            return i
 
    if(fibMMm1 and arr[n-1] == x):
        return n-1
 
    return -1

arr = [12, 24, 32, 39, 45, 50, 54] 
n = 45 
res = fibMonaccianSearch(arr, n)
if res >= 0:
    print(str(res))
else:
    print("Not Found")

4


## Задание 4
Реализуйте программный код, выполняющий сортировку матрицы
методом обмена. На вход программе дается матрица, которая
содержит в себе значения от -250 до 2000. Программа должна
возвращать матрицу в отсортированном виде.


In [63]:
#Я не уверен, что ето работает
import random 
import numpy
import time

m = 3
n = 3
matrix = numpy.empty((m, n))
for i in range(m):
    for j in range(n):
        matrix[i][j] = random.randint(-250, 2000)
print(matrix)
for row in matrix:
    i, size = 1, len(row)
    while i < size:
        if row[i - 1] > row[i]:
            row[i - 1], row[i] = row[i], row[i - 1]
            i = 1
        else:
            i += 1
print(matrix)

[[-119. 1547.  825.]
 [1385.  441. 1728.]
 [ 653. 1125. 1752.]]
[[-119.  825. 1547.]
 [ 441. 1385. 1728.]
 [ 653. 1125. 1752.]]


# Билет 4
## Задание 1
Реализуйте программный код, выполняющий поиск методом
интерполяционного поиска. На вход программе дается
отсортированный массив, который содержит в себе значения от -250
до 2000 и искомый элемент. Программа должна возвращать индекс
искомого элемента, либо уведомить пользователя, если такой
элемент отсутствует.


In [66]:
def interpolation(array, val):
    low = 0
    high = len(array)-1
    while low <= high and val >= array[low] and val <= array[high]:
        m = low + (high-low)*(val-array[low])//(array[high]-array[low])
        if array[m] == val:
            return m
        elif array[m] < val:
            low = m+1
        else:
            high = m-1
    return -1

arr = [12, 24, 32, 39, 45, 50, 54] 
n = 45 
res = interpolation(arr, n)
if res >= 0:
    print(str(res))
else:
    print("Not Found")

4


  
  ## Задание 2
       Реализуйте программный код, выполняющий сортировку матрицы
методом Шелла. На вход программе дается матрица, которая
содержит в себе значения от -250 до 2000. Программа должна
возвращать матрицу в отсортированном виде.


In [5]:
#Я не уверен, что ето работает
import random 
import numpy
import time

def shell_sort(arr):
    last_index = len(arr) - 1
    step = len(arr) // 2
    while step > 0:
        for i in range(step, last_index + 1, 1):
            j = i
            delta = j - step
            while delta >= 0 and arr[delta] > arr[j]:
                arr[delta], arr[j] = arr[j], arr[delta]
                j = delta
                delta = j - step
        step //= 2
    return arr
        
m = 3
n = 3
matrix = numpy.empty((m, n))
for i in range(m):
    for j in range(n):
        matrix[i][j] = random.randint(-250, 2000)
print(matrix)
for row in matrix:
    row = shell_sort(row)
print(matrix)

[[1056. 1486. 1367.]
 [1716. 1770.   26.]
 [ 444.  417. -188.]]
[[1056. 1367. 1486.]
 [  26. 1716. 1770.]
 [-188.  417.  444.]]


## Задание 3
На вход программе дается строка, содержащая в себе буквы, цифры
и символы. Проверить баланс круглых скобок в строке, используя
стек.


In [10]:
class stack:
    def __init__(self):
        self.stacks=list()
    def __len__(self):
        return len(self.stacks)
        
    # добавление элемента в стек
    def add(self, el):
        self.stacks.append(el)
        
    #проверка стека на пустоту
    def testing_null(self):
        return len(self.stacks)==0
    
    #извлечение элемента из стека
    def pop(self):
        if self.testing_null():
            return None
        else:
            return self.stacks.pop()
    
    def peek(self):
        if self.testing_null():
            return None
        else:
            return self.stacks[-1]
def func(st):
    s=stack()
    for i in st:
        if i=='(':
            s.add(i)
        elif i==')':
            if s.testing_null():
                return False
            s.pop()
    return s.testing_null()

st = "((())))"
print(func(st))

False


## Задание 4
Реализуйте рехеширование с помощью метода псевдослучайных
чисел

In [ ]:
import random


class HashMap:
    keys = []
    hashes = []к

    def __init__(self, arr):
        for item in arr:
            self.add_key(item, len(arr))

    def add_key(self, item, length=None):
        if (length == None):
            length = len(self.keys)

        
        temp = hash(item) % length
        if not self.check_key_exists(item):
            if self.check(temp):
                temp = self.random_rehash(item, length)

            self.hashes.append(temp)
            self.keys.append(item)

    def print_hashes(self):
        for i in range(len(self.keys)):
            print(self.hashes[i], self.keys[i])
        print("==============")


    def random_rehash(self, key, length):
        values = [i for i in range(length * 2)]
        random.shuffle(values)
        while True:
            i = values.pop()
            temp = hash(key) % length + i
            if not self.check(temp):
                return temp

    def check(self, hash_value):
        return hash_value in self.hashes

    def check_key_exists(self, key):
        if key in self.keys:
            print(key + " exists \n")
            return True
        return False

hashes = HashMap(['dog', 'cat', 'parrot', 'hamster', 'mouse', 'horse', 'pig'])

hashes.print_hashes()
hashes.add_key('bull')
hashes.add_key('turkey')
hashes.print_hashes()
hashes.add_key('bull')
hashes.print_hashes()

# Билет 5
## Задание 4
Реализуйте рехеширование с помощью метода цепочек.


In [ ]:
class ChainMap:
    def __init__(self, n):
        self.n = n
        self.lst = [[None]] * n

        self.count = 0


    def add(self, el):
        k = (len(el) + ord(el[0])) % self.n
        if self.lst[k][0] is None:
            self.lst[k] = [el]
        else:
            self.lst[k].append(el)

        self.count += 1

    def searchEl_C(self, el):
        k = self.ind(el)
        i = 0
        if self.lst[k][i] == None:
            return -1, -1
        else:
            p = len(self.lst[k])
            while i >= len(self.lst[k]):
                if el == self.lst[k][i]:
                    break
                else:
                    i += 1

        if i < len(self.lst[k]) and el == self.lst[k][i]:
            return k, i
        else:
            return -1,-1
    def print_hashes(self):
        for i in range(len(self.lst)):
            print(self.lst[i])
        print("==============")

hashes = ChainMap(10)
# print(hashes.lst)
hashes.add('atr')
hashes.add('aie')
hashes.add('bss')
hashes.add('bsc')
hashes.add('tre')
# print(hashes.searchEl_C('atr'))

print(hashes.print_hashes())



# Билет 6
## Задание 1
Реализуйте метод простого рехеширования.


In [ ]:
class HashMap:
    keys = []
    hashes = []

    def __init__(self, arr):
        for item in arr:
            self.add_key(item, len(arr))

    def add_key(self, item, length=None):
        if (length == None):
            length = len(self.keys)

        temp = hash(item) % length
        if not self.check_key_exists(item):
            if self.check(temp):
                temp = self.rehash(item, length)

            self.hashes.append(temp)
            self.keys.append(item)

    def print_hashes(self):
        for i in range(len(self.keys)):
            print(self.hashes[i], self.keys[i])
        print("==============")


    def check(self, hash_value):
        return hash_value in self.hashes

    def check_key_exists(self, key):
        if key in self.keys:
            print(key + " exists \n")
            return True
        return False
            
    def rehash(self, key, length):
        i = 1
        while True:
            temp = hash(key) % length + i
            if not self.check(temp):
                return temp
            i = i + 1
            
hashes = HashMap(['dog', 'cat', 'parrot', 'hamster', 'mouse', 'horse', 'pig'])

hashes.print_hashes()
hashes.add_key('bull')
hashes.add_key('turkey')
hashes.print_hashes()
hashes.add_key('bull')
hashes.print_hashes()

## Задание 2
Реализуйте программный код, выполняющий сортировку матрицы
турнирным методом. На вход программе дается матрица, которая
содержит в себе значения от -250 до 2000. Программа должна
возвращать матрицу в отсортированном виде.



In [4]:
#Я не уверен, что ето работает
import random 
import numpy
import time
def tournament_sort(arr):
    tree = [None] * 2 * (len(arr) + len(arr) % 2)
    index = len(tree) - len(arr) - len(arr) % 2
    
    for i, v in enumerate(arr):
        tree[index + i] = (i, v)
    
    for j in range(len(arr)):
        n = len(arr)
        index = len(tree) - len(arr) - len(arr) % 2
        while index > -1:
            n = (n + 1) // 2
            for i in range(n):
                i = max(index + i * 2, 1) 
                if tree[i] != None and tree[i + 1] != None:
                    if tree[i][1] < tree[i + 1][1]:
                        tree[i // 2] = tree[i]
                    else:
                        tree[i // 2] = tree[i + 1]
                else:
                    tree[i // 2] = tree[i] if tree[i] != None else tree[i + 1]
            index -= n

        index, x = tree[0]
        arr[j] = x
        tree[len(tree) - len(arr) - len(arr) % 2 + index] = None
    return arr
m = 3
n = 3

matrix = numpy.empty((m, n))
for i in range(m):
    for j in range(n):
        matrix[i][j] = random.randint(-250, 2000)
print(matrix)
for row in matrix:
    row = tournament_sort(row)
print(matrix)

[[1382. 1660.  900.]
 [1453.   98. 1114.]
 [ 613.  757.  786.]]
[[ 900. 1382. 1660.]
 [  98. 1114. 1453.]
 [ 613.  757.  786.]]


## Задание 3
На вход программе дается строка, содержащая слова, разделенные
пробелом. Используя стек, осуществить запись слов в обратном
порядке: первое слово становится последним, второе –
предпоследним и т.д.




In [9]:
class stack:
    def __init__(self):
        self.stacks=list()
    def __len__(self):
        return len(self.stacks)
        
    # добавление элемента в стек
    def add(self, el):
        self.stacks.append(el)
        
    #проверка стека на пустоту
    def testing_null(self):
        return len(self.stacks)==0
    
    #извлечение элемента из стека
    def pop(self):
        if self.testing_null():
            return None
        else:
            return self.stacks.pop()

st = "хотеться большинство разводить план яркий исключать установка бабах"
out = ""
my_stack = stack()
for i in st.split():
    my_stack.add(i)
    
while not my_stack.testing_null():
    out += my_stack.pop() + " "
print(out)


бабах установка исключать яркий план разводить большинство хотеться 


# Билет 7
## Задание 1
Реализовать поиска подстроки в строке методом Бойера-Мура. На
вход программе подается строка и подстрока. Программа должна
быть не чувствительной к строке и регистру


In [12]:
#Бойера-Мура
def createShiftTable(t):
    S = set()  # уникальные символы в образе
    M = len(t) # число символов в образе
    d = {}     # словарь смещений
    
    for i in range(M-2, -1, -1): # итерации с предпоследнего символа
        if t[i] not in S:        # если символ еще не добавлен в таблицу
            d[t[i]] = M-i-1
            S.add(t[i])
    
    if t[M-1] not in S:     # отдельно формируем последний символ
        d[t[M-1]] = M
    
    d['*'] = M              # смещения для прочих символов
    return d

def bmh(s, t):
    s = s.lower()
    t = t.lower()
    N = len(s)
    M = len(t)
    d = createShiftTable(t)
    if N >= M:
        i = M-1       # счетчик проверяемого символа в строке
    
        while(i < N):
            k = 0
            j = 0
            flBreak = False
            for j in range(M-1, -1, -1):
                if s[i-k] != t[j]:
                    if j == M-1:
                        off = d[s[i]] if d.get(s[i], False) else d['*']  # смещение, если не равен последний символ образа
                    else:
                        off = d[t[j]]   # смещение, если не равен не последний символ образа
    
                    i += off    # смещение счетчика строки
                    flBreak = True  # если несовпадение символа, то flBreak = True
                    break
    
                k += 1          # смещение для сравниваемого символа в строке
    
            if not flBreak:          # если дошли до начала образа, значит, все его символы совпали
                return i-k+1
                break
    return -1

s = "abccbaacbe"
t = "aacb"
bmh(s,t)

5

## Задание 2 
Реализуйте программный код, выполняющий сортировку матрицы
методом быстрой сортировки. На вход программе дается матрица,
которая содержит в себе значения от -250 до 2000. Программа
должна возвращать матрицу в отсортированном виде.


In [11]:
#Я не уверен, что ето работает
import random 
import numpy
import time
def partition(arr, low, high):
    pivot = arr[(low + high) // 2]
    i = low - 1
    j = high + 1
    while True:
        i += 1
        while arr[i] < pivot:
            i += 1
        j -= 1
        while arr[j] > pivot:
            j -= 1
        if i >= j:
            return j
        arr[i], arr[j] = arr[j], arr[i]
def quick_sort(arr):  
    def _quick_sort(items, low, high):
        if low < high:
            split_index = partition(items, low, high)
            _quick_sort(items, low, split_index)
            _quick_sort(items, split_index + 1, high)
    _quick_sort(arr, 0, len(arr) - 1)
    return arr
    
m = 3
n = 3

matrix = numpy.empty((m, n))
for i in range(m):
    for j in range(n):
        matrix[i][j] = random.randint(-250, 2000)
print(matrix)
for row in matrix:
    row = tournament_sort(row)
print(matrix)

[[1879. 1132.  612.]
 [1559. 1226.  408.]
 [ 488. 1901. 1211.]]
[[ 612. 1132. 1879.]
 [ 408. 1226. 1559.]
 [ 488. 1211. 1901.]]


## Задание 3
Реализуйте рехеширование с помощью метода псевдослучайных
чисел.



In [ ]:
import random


class HashMap:
    keys = []
    hashes = []к

    def __init__(self, arr):
        for item in arr:
            self.add_key(item, len(arr))

    def add_key(self, item, length=None):
        if (length == None):
            length = len(self.keys)

        
        temp = hash(item) % length
        if not self.check_key_exists(item):
            if self.check(temp):
                temp = self.random_rehash(item, length)

            self.hashes.append(temp)
            self.keys.append(item)

    def print_hashes(self):
        for i in range(len(self.keys)):
            print(self.hashes[i], self.keys[i])
        print("==============")


    def random_rehash(self, key, length):
        values = [i for i in range(length * 2)]
        random.shuffle(values)
        while True:
            i = values.pop()
            temp = hash(key) % length + i
            if not self.check(temp):
                return temp

    def check(self, hash_value):
        return hash_value in self.hashes

    def check_key_exists(self, key):
        if key in self.keys:
            print(key + " exists \n")
            return True
        return False

hashes = HashMap(['dog', 'cat', 'parrot', 'hamster', 'mouse', 'horse', 'pig'])

hashes.print_hashes()
hashes.add_key('bull')
hashes.add_key('turkey')
hashes.print_hashes()
hashes.add_key('bull')
hashes.print_hashes()

# Билет 8
## Задание 3
Реализуйте рехеширование с помощью метода цепочек.




In [ ]:
class ChainMap:
    def __init__(self, n):
        self.n = n
        self.lst = [[None]] * n

        self.count = 0


    def add(self, el):
        k = (len(el) + ord(el[0])) % self.n
        if self.lst[k][0] is None:
            self.lst[k] = [el]
        else:
            self.lst[k].append(el)

        self.count += 1

    def searchEl_C(self, el):
        k = self.ind(el)
        i = 0
        if self.lst[k][i] == None:
            return -1, -1
        else:
            p = len(self.lst[k])
            while i >= len(self.lst[k]):
                if el == self.lst[k][i]:
                    break
                else:
                    i += 1

        if i < len(self.lst[k]) and el == self.lst[k][i]:
            return k, i
        else:
            return -1,-1
    def print_hashes(self):
        for i in range(len(self.lst)):
            print(self.lst[i])
        print("==============")

hashes = ChainMap(10)
# print(hashes.lst)
hashes.add('atr')
hashes.add('aie')
hashes.add('bss')
hashes.add('bsc')
hashes.add('tre')
# print(hashes.searchEl_C('atr'))

print(hashes.print_hashes())



## Задание 4
Реализуйте программный код, выполняющий сортировку матрицы
пирамидальной методом. На вход программе дается матрица,
которая содержит в себе значения от -250 до 2000. Программа
должна возвращать матрицу в отсортированном виде.

In [12]:
def heapify(nums, heap_size, root_index):  
    largest = root_index
    left_child = (2 * root_index) + 1
    right_child = (2 * root_index) + 2
    if left_child < heap_size and nums[left_child] > nums[largest]:
        largest = left_child
    if right_child < heap_size and nums[right_child] > nums[largest]:
        largest = right_child
    if largest != root_index:
        nums[root_index], nums[largest] = nums[largest], nums[root_index]
        heapify(nums, heap_size, largest)
def heap_sort(arr):  
    n = len(arr)
    for i in range(n, -1, -1):
        heapify(arr, n, i)
    for i in range(n - 1, 0, -1):
        arr[i], arr[0] = arr[0], arr[i]
        heapify(arr, i, 0)
    
m = 3
n = 3

matrix = numpy.empty((m, n))
for i in range(m):
    for j in range(n):
        matrix[i][j] = random.randint(-250, 2000)
print(matrix)
for row in matrix:
    row = heap_sort(row)
print(matrix)

[[ 904.  525.  791.]
 [ 472.  -14. -250.]
 [1876.  252. 1521.]]
[[ 525.  791.  904.]
 [-250.  -14.  472.]
 [ 252. 1521. 1876.]]


# Билет 10
## Задание 1
Реализовать поиска подстроки в строке методом Бойера-Мура. На
вход программе подается строка и подстрока. Программа должна
быть чувствительной к строке и регистру




In [ ]:
#Бойера-Мура
def createShiftTable(t):
    S = set()  # уникальные символы в образе
    M = len(t) # число символов в образе
    d = {}     # словарь смещений
    
    for i in range(M-2, -1, -1): # итерации с предпоследнего символа
        if t[i] not in S:        # если символ еще не добавлен в таблицу
            d[t[i]] = M-i-1
            S.add(t[i])
    
    if t[M-1] not in S:     # отдельно формируем последний символ
        d[t[M-1]] = M
    
    d['*'] = M              # смещения для прочих символов
    return d

def bmh(s, t):

    N = len(s)
    M = len(t)
    d = createShiftTable(t)
    if N >= M:
        i = M-1       # счетчик проверяемого символа в строке
    
        while(i < N):
            k = 0
            j = 0
            flBreak = False
            for j in range(M-1, -1, -1):
                if s[i-k] != t[j]:
                    if j == M-1:
                        off = d[s[i]] if d.get(s[i], False) else d['*']  # смещение, если не равен последний символ образа
                    else:
                        off = d[t[j]]   # смещение, если не равен не последний символ образа
    
                    i += off    # смещение счетчика строки
                    flBreak = True  # если несовпадение символа, то flBreak = True
                    break
    
                k += 1          # смещение для сравниваемого символа в строке
    
            if not flBreak:          # если дошли до начала образа, значит, все его символы совпали
                return i-k+1
                break
    return -1

s = "abccbaacbe"
t = "aacb"
bmh(s,t)

## Задание 2
 Реализуйте метод простого рехеширования.

In [ ]:
class HashMap:
    keys = []
    hashes = []

    def __init__(self, arr):
        for item in arr:
            self.add_key(item, len(arr))

    def add_key(self, item, length=None):
        if (length == None):
            length = len(self.keys)

        temp = hash(item) % length
        if not self.check_key_exists(item):
            if self.check(temp):
                temp = self.rehash(item, length)

            self.hashes.append(temp)
            self.keys.append(item)

    def print_hashes(self):
        for i in range(len(self.keys)):
            print(self.hashes[i], self.keys[i])
        print("==============")


    def check(self, hash_value):
        return hash_value in self.hashes

    def check_key_exists(self, key):
        if key in self.keys:
            print(key + " exists \n")
            return True
        return False
            
    def rehash(self, key, length):
        i = 1
        while True:
            temp = hash(key) % length + i
            if not self.check(temp):
                return temp
            i = i + 1
            
hashes = HashMap(['dog', 'cat', 'parrot', 'hamster', 'mouse', 'horse', 'pig'])

hashes.print_hashes()
hashes.add_key('bull')
hashes.add_key('turkey')
hashes.print_hashes()
hashes.add_key('bull')
hashes.print_hashes()

## Задание 3
Реализуйте программный код, выполняющий сортировку матрицы
методом выбора. На вход программе дается матрица, которая
содержит в себе значения от -250 до 2000. Программа должна
возвращать матрицу в отсортированном виде.

In [ ]:
#Я не уверен, что ето работает
import random 
import numpy
import time

def selection_sort(arr):
    for n in range(len(arr)):
        i=0
        while i < len(arr[0]) - 1:
            m = i
            j = i + 1
            while j < len(arr[0]):
                if arr[n][j] < arr[n][m]:
                    m = j
                j += 1
            arr[n][i], arr[n][m] = arr[n][m], arr[n][i]
            i += 1
    return arr

m = 3
n = 3
matrix = numpy.empty((m, n))
for i in range(m):
    for j in range(n):
        matrix[i][j] = random.randint(-250, 2000)
print(matrix)
selection_sort(matrix)
print(matrix)


## Задание 4
Реализуйте программный код, выполняющий поиск методом
бинарного дерева. На вход программе дается отсортированный
массив, который содержит в себе значения от -250 до 2000 и
искомый элемент. Программа должна возвращать индекс искомого
элемента, либо уведомить пользователя, если такой элемент
отсутствует.

In [ ]:
class TreeNode:
    def __init__(self, value):
        self.value=value
        self.right=None
        self.left=None
    def add(self, mas):
        if mas<self.value:
            if self.left is None:
                self.left=TreeNode(mas)
            else:
                self.left.add( mas)
        else:
            if self.right is None:
                self.right=TreeNode(mas)
            else:
                self.right.add(mas)
        
            
    def search(self, nl):
        if nl and self and self.value is not None:
            if nl>self.value and self.right:
                self=self.right.search(nl)
            elif nl<self.value and self.left:
                self=self.left.search(nl)
            elif(nl==self.value):
                print("Элемент найден")
                return True
            else:
                print("Элемент не найден")
                return None
            
        else:
            print("Элемент не найден")
            return None
        return True
    def deleted(self):
        if self.right is not None:
            self.value=self.right.value
            self.right.deleted()
        elif self.left is not None:
            self.value=self.left.value
            self.left.deleted()
        elif (self.left is None) and (self.right is None):
            self.value=None
    
    def delete(self, i):
        self.pre_order(i).deleted()
        
    def pr(self):
        if self.left:
            self.left.pr()
        print(self.value)
        if self.right:
            self.right.pr()
arr = [12, 24, 32, 39, 45, 50, 54] 
n = 45 
tree=TreeNode(arr[0])
for i in range(1, len(arr)):
    tree.add(arr[i])
print(tree.search(n) )